### ISSUE TITLE
Mega Energy Reward Formatting

### ISSUE THREAD

**Issue by PartTimeJS** [ccev/pogoinfo#1]
https://github.com/ccev/pogoinfo/blob/info/events/active.json

Mega Energy Reward formatting seems borked. 

`"Battle another trainer": [
                "5 Mega Energy (Blastoise",
                "003_00",
                "006_00"
            ]`

**Comment by ccev** [comment]
do people use this info anyway? if so, i can try to let it stay correct

**Comment by ccev** [comment]
this will be fixed in v2.

https://github.com/ccev/pogoinfo/blob/v2/active/quests.json
