### ISSUE TITLE
Suggestion: Shiny variant in json files (if possible)

### ISSUE THREAD

**Issue by Chefkeks** [ccev/pogoinfo#2]
Hey there,

don't know if it's possible, but would be nice if the json files, eg. raid-bosses, would include the shiny variant if available instead of the non-shiny variant. So for example Entei currently in the raid-bosses.json would then be:
```   
 "5": [
        "244_00_shiny"
    ],
```
instead of 
```   
 "5": [
        "244_00"
    ],
```

If it's not possible, no big deal.

Thanks
🍪 ✌️

**Comment by ccev** [comment]
I don't think doing it this way is beneficial. On the v2 branch I'm currently working on, I'll include a list of available shinies, you could then use that to generate the icon name yourself.

**Comment by Chefkeks** [comment]
Hadn't noticed the V2 branch!
Thanks for pointing to it. To generate the icon name myself is then no issue of course.

So will wait for V2 to become the new master and adjust things then.
Btw. thanks a lot for your overall work!

Cheers
🍪 ✌️
